spring:
  profiles: default
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

hm-service:
  datasource:
    jdbc-url: jdbc:mysql://192.168.3.203:3306/ps_service?serverTimezone=UTC
    username: iqsbz
    password: '!Sqisoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver